# Generated by Django 3.1.1 on 2020-11-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zespoly',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
