# Generated by Django 3.1.1 on 2020-11-18 19:11

from django.db import migrations, models
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0002_zespoly_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='zespoly',
            name='camera',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='zespoly',
            name='exif',
            field=exiffield.fields.ExifField(default={}, editable=False),
        ),
    ]
