# Generated by Django 3.1.1 on 2020-11-18 19:41

from django.db import migrations, models
import muzyka.models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0006_zespoly_meta'),
    ]


