# Generated by Django 3.1.1 on 2020-11-18 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0008_remove_zespoly_meta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zespoly',
            name='slug',
        ),
    ]
