# Generated by Django 3.1.1 on 2020-11-18 20:09

from django.db import migrations, models
import muzyka.models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0009_remove_zespoly_slug'),
    ]

