# Generated by Django 3.1.1 on 2020-11-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0010_auto_20201118_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='zespoly',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
