# Generated by Django 3.1.1 on 2020-11-19 16:18

from django.db import migrations, models
import exiffield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0011_zespoly_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('camera', models.CharField(editable=False, max_length=100)),
                ('exif', exiffield.fields.ExifField(default={}, editable=False)),
            ],
        ),
    ]
