# Generated by Django 3.1.1 on 2020-11-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0014_auto_20201119_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zespoly',
            name='id',
        ),
        migrations.AlterField(
            model_name='zespoly',
            name='slug',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
