# Generated by Django 3.1.1 on 2020-11-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0017_auto_20201119_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tlo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='media')),
            ],
        ),
    ]
