# Generated by Django 3.1.1 on 2020-11-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0018_tlo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tlo',
        ),
    ]
