# Generated by Django 3.1.1 on 2020-11-22 18:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0022_auto_20201122_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='zespoly',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muzyka.category'),
            preserve_default=False,
        ),
    ]
