# Generated by Django 3.1.1 on 2020-11-22 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0026_remove_zespoly_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='zespoly',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='muzyka.category'),
        ),
    ]
