# Generated by Django 3.1.1 on 2020-11-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0027_zespoly_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zespoly',
            options={'ordering': ('-nazwa',)},
        ),
    ]
