# Generated by Django 3.1.1 on 2020-11-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0029_auto_20201126_2053'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Zespoly',
            new_name='Galeria',
        ),
    ]
