# Generated by Django 3.1.1 on 2020-12-09 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0030_auto_20201126_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='muzyka.category'),
        ),
    ]
