# Generated by Django 3.1.1 on 2020-12-15 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0031_auto_20201209_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='Fnum',
            field=models.CharField(default='111', editable=False, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='galeria',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories_cat', to='muzyka.category'),
        ),
    ]
