# Generated by Django 3.1.1 on 2020-12-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0032_auto_20201215_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='ogniskowa',
            field=models.CharField(default='111', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
