# Generated by Django 3.1.1 on 2020-12-15 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0034_galeria_ekspozycja'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='firma',
            field=models.CharField(default='111', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
