# Generated by Django 3.1.1 on 2020-12-15 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0035_galeria_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='czas_tworzenia',
            field=models.CharField(default='222', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
