# Generated by Django 3.1.1 on 2020-12-17 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0037_galeria_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='czas_tworzenia',
        ),
    ]
