# Generated by Django 3.1.1 on 2020-12-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0038_remove_galeria_czas_tworzenia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='data',
            field=models.CharField(editable=False, max_length=10),
        ),
    ]
