# Generated by Django 3.1.1 on 2020-12-17 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0039_auto_20201217_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='data',
            field=models.TextField(editable=False, max_length=10),
        ),
    ]
