# Generated by Django 3.1.1 on 2020-12-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0040_auto_20201217_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galeria',
            name='data',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
