# Generated by Django 3.1.1 on 2021-04-05 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0044_galeria_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='user',
        ),
    ]
