# Generated by Django 3.1.1 on 2021-04-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0046_galeria_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zdjecie',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
