# Generated by Django 3.1.1 on 2021-04-07 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0047_profile_zdjecie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='zdjecie',
            new_name='zdjecie_profilowe',
        ),
    ]
