# Generated by Django 3.1.1 on 2021-04-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0048_auto_20210407_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='zdjecie_profilowe',
        ),
    ]
