# Generated by Django 3.1.1 on 2021-04-07 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0049_remove_profile_zdjecie_profilowe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='zdjecie_profilowe',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
