# Generated by Django 3.1.1 on 2021-06-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0051_remove_profile_zdjecie_profilowe'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo_user',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
