# Generated by Django 3.1.1 on 2021-06-19 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0054_remove_galeria_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galeria',
            name='Fnum',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='Xres',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='Yres',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='camera',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='data',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='ekspozycja',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='exif',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='firma',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='iso',
        ),
        migrations.RemoveField(
            model_name='galeria',
            name='ogniskowa',
        ),
    ]
