# Generated by Django 3.1.1 on 2021-06-22 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0055_auto_20210619_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulubionyalbum',
            name='ocena',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
