# Generated by Django 3.1.1 on 2021-06-23 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0057_auto_20210623_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocenaalbumu',
            old_name='albumy',
            new_name='album',
        ),
    ]
