# Generated by Django 3.1.1 on 2021-07-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0058_auto_20210623_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeria',
            name='Zespol',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='galeria',
            name='nazwa',
            field=models.CharField(max_length=60),
        ),
    ]
