# Generated by Django 3.1.1 on 2021-07-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muzyka', '0059_auto_20210704_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeria',
            old_name='Zespol',
            new_name='zespol',
        ),
    ]
